# FUNÇÃO: Monitorar os pods, se algum falhar: criar novamente

# CRIAR:
# kubectl create -f replica-set-definition.yaml

# LISTAR:
# kubectl get replicaset

# REPLACE: "usado para atualizar um que tenha sido criado"
# kubectl replace -f replica-set-definition.yaml
# ou
# kubectl scale --replicas=6 -f replica-set-definition.yaml
# ou
# kubectl scale --replicas=6 replicaset myapp-replica-set

# EDITAR:
# kubectl edit replicaset myapp-replica-set

# DELETE: "também deleta os pods"
# kubectl delete replicaset myapp-replica-set

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica-set
  labels:
    app: myapp
    tier: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
        tier: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx