# ESSE POD FICA GERANDO LOGS ALEATÓRIOS
apiVersion: v1
kind: Pod
metadata:
  name: event-simulator
  namespace: default
spec:
  containers:
  - name: event-simulator
    image: kodekloud/event-simulator
    imagePullPolicy: IfNotPresent
    env:
    - name: LOG_HANDLERS
      value: file
  restartPolicy: Always
