apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webapp-food
  name: webapp-food
spec:
  containers:
  - image: kodekloud/ecommerce:food
    imagePullPolicy: IfNotPresent
    name: webapp-food
    ports:
    - containerPort: 8080
      protocol: TCP
  restartPolicy: Always
