# FUNÇÃO: Direcionar um pod a um determinado tipo de node

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
  nodeSelector:
    size: Large # Esse label deve estar presente no node específico