Função: Definir a quantidade de recursos de hardware que pode ser usado

CPU:
  1 CPU = {
    1 AWS vCPU
    1 GCP Core
    1 Azure Core
    1 Hyperthread
  }

MEM:
  1G = {
    1 G (Gigabyte) = 1,000,000,000 bytes
    1 M (Megabyte) = 1,000,000 bytes
    1 K (Kilobyte) = 1,000 bytes

    1 Gi (Gibibyte) = 1,073,741,824 bytes
    1 Mi (Mebibyte) = 1,048,576 bytes
    1 Ki (Kibibyte) = 1,024 bytes
  }

Por padrão o kubernets define:
  cpu: 1
  memory: 512

Um container não pode usar mais CPU que o seu limite, então o kubernetes estrangula
o container para se manter nesse limite.
No entanto, se um container usar contantemente mais memoria que o limite, o pod será encerrado!

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp-pod
spec:
  containers:
  - name: myapp-pod
    image: nginx
    ports:
      - containerPort: 80
    resourses:
      requests:
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2

Erros:
  The status OOMKilled indicates that it is failing because the pod ran out of memory.
