Função: Criar conta de serviço para algum sistema acessar o kubernetes


# Criar
$ k create serviceaccount dashboard-sa

# Quando a Service Account é criada, ela irá gerar um token, esse token deverá ser usado no applicado externo
$ k describe serviceaccount dashboard-sa

# Para obter esse token "secret", ele deve ser usado ocmo um "Bearer Qeqsdq..."
$ k describe secret dashboard-sa-token-kbbdm

# Caso a aplicação que irá fazer acesso esteja dentro do proprio kubernetes, pode usar uma forma
# mais simplificada, montando o compo serviceAccountName no pod
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
  serviceAccountName: dashboard-sa

# Obs.: Por default, qualquer pode já vem com a ServiceAccount "default" montada, que é muito restrita
# pasa acessar as informações dela:

/usr/run/secrets/kubernetes.io/serviceaccount {
  ca.crt
  namespace
  token -> Aqui está o token
}

# Obs.: Se não quiser que isso seja feito automaticamente, basta setar que não quer:
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
  automountServiceAccountToken: false